### PR TITLE
Add DragonFly snapshot for 235d774 (2016-03-18)

### PR DESCRIPTION
**Pull request by mneumann**

### CODE REVIEW

**Comment by mneumann** [comment]
btw, this snapshot is built by applying the following patch: http://ntecs.de/downloads/rust/rust-2016-03-18.patch

**Comment by mneumann** [comment]
@dhuseby : ping

**Comment by dhuseby** [comment]
Thanks!  Sorry, I was on an airplane to Taipei yesterday.  I've been AFK for the last 48 hours.

**Comment by mneumann** [comment]
No problem :). btw, when this hits the rust repo, Rust should build on DragonFly without any patches.

**Pull request merged**
